
spring:
  application.name: sabong
  profiles:
    active: #spring.profiles.active#
  mvc.pathmatch.matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.generate_statistics: true
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
server:
  port: 8181


appconfig:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 1000 # Number of objects in each cache entry

  cors:
    allowed-origins: 'http://localhost:4200,https://localhost:4200'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${spring.application.name}-alert,X-${spring.application.name}-error,X-${spring.application.name}-params'
    allow-credentials: true
    max-age: 1800

  jwt:
    # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
    base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
    # Token is valid 24 hours
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000
  # security
  authRequest:
    - /api/**
    - /admin/**
    - /admin/swagger-ui/**
  ignoredRequest:
    #       Swagger UI v2
    - v2/api-docs,
    - /swagger-resources
    - swagger-resources
    - /swagger-resources/**
    - swagger-resources/**
    - /configuration/ui
    - configuration/ui
    - /configuration/security
    - configuration/security
    - /swagger-ui.html
    - swagger-ui.html
    - webjars/**
    #       Swagger UI v3
    - /v3/api-docs/**
    - v3/api-docs/**
    - /swagger-ui/**
    - swagger-ui/**
    #       Actuators
    - /actuator/**
    - /health/**
    #       mine
    - /login
    - /logout
    - /applications/**
    - /instances/**
    - /eureka/**
  #      - /api/**
  permitAll:
    - index
    - index.html
    - '**.css'
    - '**.js'
    - /api/authenticate
    - /eureka/**
    - /assets/**
    - /login
    - swagger-ui/**
    - /swagger-ui/**
    - v3/api-docs/**
    - /v3/api-docs/**
    - /eureka/**
  #      - /api/**
  #      - /assets/**
  #      - /login

  corsFilter:
    - /management/**
    - /v2/api-docs/**
    - /v3/api-docs/**
    - /swagger-resources
    - /swagger-ui/**
    - /admin/**